version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: calculadora-inferno-minion-fuel
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: production
      SECRET_KEY: bba7e0cb777b1f6ce2830cdad5b2b9b2ef875d7814be3ed6  # Reemplaza con tu clave secreta
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    container_name: redis-container

volumes:
  data:
